spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:9090   # your payment microservice port
          predicates:
            - Path=/payment/**
